/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RequestId = IDL.Nat;
export const VolunteerId = IDL.Nat;
export const AssignmentId = IDL.Nat;
export const AssignmentStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'status' : AssignmentStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'requestId' : RequestId,
  'volunteerId' : VolunteerId,
  'acceptedAt' : Timestamp,
});
export const Urgency = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const ResourceType = IDL.Variant({
  'other' : IDL.Null,
  'food' : IDL.Null,
  'education' : IDL.Null,
  'shelter' : IDL.Null,
  'medical' : IDL.Null,
});
export const NgoId = IDL.Nat;
export const CreateRequestInput = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'title' : IDL.Text,
  'urgency' : Urgency,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'resourceType' : ResourceType,
  'ngoId' : NgoId,
  'quantity' : IDL.Nat,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const ResourceRequest = IDL.Record({
  'id' : RequestId,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : RequestStatus,
  'title' : IDL.Text,
  'urgency' : Urgency,
  'assignedVolunteers' : IDL.Vec(VolunteerId),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'resourceType' : ResourceType,
  'ngoId' : NgoId,
  'quantity' : IDL.Nat,
});
export const NGO = IDL.Record({
  'id' : NgoId,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isVerified' : IDL.Bool,
  'contactEmail' : IDL.Text,
});
export const Volunteer = IDL.Record({
  'id' : VolunteerId,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'completedTasks' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'rating' : IDL.Float64,
  'skills' : IDL.Vec(IDL.Text),
});
export const CreateNGOInput = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const CreateVolunteerInput = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'name' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : ChatRole,
  'timestamp' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'assignVolunteer' : IDL.Func(
      [RequestId, VolunteerId],
      [IDL.Opt(Assignment)],
      [],
    ),
  'createRequest' : IDL.Func([CreateRequestInput], [ResourceRequest], []),
  'detectLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllNGOs' : IDL.Func([], [IDL.Vec(NGO)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ResourceRequest)], ['query']),
  'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'getAvailableVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'getMapApiKey' : IDL.Func([], [IDL.Text], ['query']),
  'getNearbyRequests' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(ResourceRequest)],
      ['query'],
    ),
  'getRequestsByNgo' : IDL.Func([NgoId], [IDL.Vec(ResourceRequest)], ['query']),
  'registerNGO' : IDL.Func([CreateNGOInput], [NGO], []),
  'registerVolunteer' : IDL.Func([CreateVolunteerInput], [Volunteer], []),
  'sendChatMessage' : IDL.Func([IDL.Vec(ChatMessage)], [IDL.Text], []),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'setGoogleCloudTranslationApiKey' : IDL.Func([IDL.Text], [], []),
  'setGoogleMapsApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformTranslation' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'translateText' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateRequestStatus' : IDL.Func([RequestId, RequestStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RequestId = IDL.Nat;
  const VolunteerId = IDL.Nat;
  const AssignmentId = IDL.Nat;
  const AssignmentStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'status' : AssignmentStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'requestId' : RequestId,
    'volunteerId' : VolunteerId,
    'acceptedAt' : Timestamp,
  });
  const Urgency = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ResourceType = IDL.Variant({
    'other' : IDL.Null,
    'food' : IDL.Null,
    'education' : IDL.Null,
    'shelter' : IDL.Null,
    'medical' : IDL.Null,
  });
  const NgoId = IDL.Nat;
  const CreateRequestInput = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'title' : IDL.Text,
    'urgency' : Urgency,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'resourceType' : ResourceType,
    'ngoId' : NgoId,
    'quantity' : IDL.Nat,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const ResourceRequest = IDL.Record({
    'id' : RequestId,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : RequestStatus,
    'title' : IDL.Text,
    'urgency' : Urgency,
    'assignedVolunteers' : IDL.Vec(VolunteerId),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'resourceType' : ResourceType,
    'ngoId' : NgoId,
    'quantity' : IDL.Nat,
  });
  const NGO = IDL.Record({
    'id' : NgoId,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isVerified' : IDL.Bool,
    'contactEmail' : IDL.Text,
  });
  const Volunteer = IDL.Record({
    'id' : VolunteerId,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'completedTasks' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'rating' : IDL.Float64,
    'skills' : IDL.Vec(IDL.Text),
  });
  const CreateNGOInput = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const CreateVolunteerInput = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'name' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : ChatRole,
    'timestamp' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'assignVolunteer' : IDL.Func(
        [RequestId, VolunteerId],
        [IDL.Opt(Assignment)],
        [],
      ),
    'createRequest' : IDL.Func([CreateRequestInput], [ResourceRequest], []),
    'detectLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllNGOs' : IDL.Func([], [IDL.Vec(NGO)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ResourceRequest)], ['query']),
    'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'getAvailableVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'getMapApiKey' : IDL.Func([], [IDL.Text], ['query']),
    'getNearbyRequests' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(ResourceRequest)],
        ['query'],
      ),
    'getRequestsByNgo' : IDL.Func(
        [NgoId],
        [IDL.Vec(ResourceRequest)],
        ['query'],
      ),
    'registerNGO' : IDL.Func([CreateNGOInput], [NGO], []),
    'registerVolunteer' : IDL.Func([CreateVolunteerInput], [Volunteer], []),
    'sendChatMessage' : IDL.Func([IDL.Vec(ChatMessage)], [IDL.Text], []),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'setGoogleCloudTranslationApiKey' : IDL.Func([IDL.Text], [], []),
    'setGoogleMapsApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformTranslation' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'translateText' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateRequestStatus' : IDL.Func(
        [RequestId, RequestStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };