/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : AssignmentId,
  'status' : AssignmentStatus,
  'completedAt' : [] | [Timestamp],
  'requestId' : RequestId,
  'volunteerId' : VolunteerId,
  'acceptedAt' : Timestamp,
}
export type AssignmentId = bigint;
export type AssignmentStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface ChatMessage {
  'content' : string,
  'role' : ChatRole,
  'timestamp' : Timestamp,
}
export type ChatRole = { 'user' : null } |
  { 'assistant' : null };
export interface CreateNGOInput {
  'lat' : number,
  'lng' : number,
  'name' : string,
  'description' : string,
  'contactEmail' : string,
}
export interface CreateRequestInput {
  'lat' : number,
  'lng' : number,
  'title' : string,
  'urgency' : Urgency,
  'description' : string,
  'deadline' : Timestamp,
  'resourceType' : ResourceType,
  'ngoId' : NgoId,
  'quantity' : bigint,
}
export interface CreateVolunteerInput {
  'lat' : number,
  'lng' : number,
  'name' : string,
  'skills' : Array<string>,
}
export interface NGO {
  'id' : NgoId,
  'lat' : number,
  'lng' : number,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isVerified' : boolean,
  'contactEmail' : string,
}
export type NgoId = bigint;
export type RequestId = bigint;
export type RequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'ongoing' : null };
export interface ResourceRequest {
  'id' : RequestId,
  'lat' : number,
  'lng' : number,
  'status' : RequestStatus,
  'title' : string,
  'urgency' : Urgency,
  'assignedVolunteers' : Array<VolunteerId>,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : Timestamp,
  'resourceType' : ResourceType,
  'ngoId' : NgoId,
  'quantity' : bigint,
}
export type ResourceType = { 'other' : null } |
  { 'food' : null } |
  { 'education' : null } |
  { 'shelter' : null } |
  { 'medical' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type Urgency = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface Volunteer {
  'id' : VolunteerId,
  'lat' : number,
  'lng' : number,
  'completedTasks' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'rating' : number,
  'skills' : Array<string>,
}
export type VolunteerId = bigint;
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'assignVolunteer' : ActorMethod<[RequestId, VolunteerId], [] | [Assignment]>,
  'createRequest' : ActorMethod<[CreateRequestInput], ResourceRequest>,
  'detectLanguage' : ActorMethod<[string], string>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllNGOs' : ActorMethod<[], Array<NGO>>,
  'getAllRequests' : ActorMethod<[], Array<ResourceRequest>>,
  'getAllVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'getAvailableVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'getMapApiKey' : ActorMethod<[], string>,
  'getNearbyRequests' : ActorMethod<
    [number, number, number],
    Array<ResourceRequest>
  >,
  'getRequestsByNgo' : ActorMethod<[NgoId], Array<ResourceRequest>>,
  'registerNGO' : ActorMethod<[CreateNGOInput], NGO>,
  'registerVolunteer' : ActorMethod<[CreateVolunteerInput], Volunteer>,
  'sendChatMessage' : ActorMethod<[Array<ChatMessage>], string>,
  'setGeminiApiKey' : ActorMethod<[string], undefined>,
  'setGoogleCloudTranslationApiKey' : ActorMethod<[string], undefined>,
  'setGoogleMapsApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformTranslation' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'translateText' : ActorMethod<[string, string], string>,
  'updateRequestStatus' : ActorMethod<[RequestId, RequestStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];