/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ResourceRequest {
    id: RequestId;
    lat: number;
    lng: number;
    status: RequestStatus;
    title: string;
    urgency: Urgency;
    assignedVolunteers: Array<VolunteerId>;
    createdAt: Timestamp;
    description: string;
    deadline: Timestamp;
    resourceType: ResourceType;
    ngoId: NgoId;
    quantity: bigint;
}
export interface CreateNGOInput {
    lat: number;
    lng: number;
    name: string;
    description: string;
    contactEmail: string;
}
export type NgoId = bigint;
export type VolunteerId = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CreateVolunteerInput {
    lat: number;
    lng: number;
    name: string;
    skills: Array<string>;
}
export interface CreateRequestInput {
    lat: number;
    lng: number;
    title: string;
    urgency: Urgency;
    description: string;
    deadline: Timestamp;
    resourceType: ResourceType;
    ngoId: NgoId;
    quantity: bigint;
}
export interface ChatMessage {
    content: string;
    role: ChatRole;
    timestamp: Timestamp;
}
export type AssignmentId = bigint;
export interface Volunteer {
    id: VolunteerId;
    lat: number;
    lng: number;
    completedTasks: bigint;
    name: string;
    isAvailable: boolean;
    rating: number;
    skills: Array<string>;
}
export type RequestId = bigint;
export interface NGO {
    id: NgoId;
    lat: number;
    lng: number;
    name: string;
    createdAt: Timestamp;
    description: string;
    isVerified: boolean;
    contactEmail: string;
}
export interface Assignment {
    id: AssignmentId;
    status: AssignmentStatus;
    completedAt?: Timestamp;
    requestId: RequestId;
    volunteerId: VolunteerId;
    acceptedAt: Timestamp;
}
export enum AssignmentStatus {
    active = "active",
    cancelled = "cancelled",
    completed = "completed"
}
export enum ChatRole {
    user = "user",
    assistant = "assistant"
}
export enum RequestStatus {
    pending = "pending",
    completed = "completed",
    ongoing = "ongoing"
}
export enum ResourceType {
    other = "other",
    food = "food",
    education = "education",
    shelter = "shelter",
    medical = "medical"
}
export enum Urgency {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export interface backendInterface {
    assignVolunteer(requestId: RequestId, volunteerId: VolunteerId): Promise<Assignment | null>;
    createRequest(input: CreateRequestInput): Promise<ResourceRequest>;
    detectLanguage(text: string): Promise<string>;
    getAllAssignments(): Promise<Array<Assignment>>;
    getAllNGOs(): Promise<Array<NGO>>;
    getAllRequests(): Promise<Array<ResourceRequest>>;
    getAllVolunteers(): Promise<Array<Volunteer>>;
    getAvailableVolunteers(): Promise<Array<Volunteer>>;
    getMapApiKey(): Promise<string>;
    getNearbyRequests(lat: number, lng: number, radiusKm: number): Promise<Array<ResourceRequest>>;
    getRequestsByNgo(ngoId: NgoId): Promise<Array<ResourceRequest>>;
    registerNGO(input: CreateNGOInput): Promise<NGO>;
    registerVolunteer(input: CreateVolunteerInput): Promise<Volunteer>;
    sendChatMessage(messages: Array<ChatMessage>): Promise<string>;
    setGeminiApiKey(key: string): Promise<void>;
    setGoogleCloudTranslationApiKey(key: string): Promise<void>;
    setGoogleMapsApiKey(key: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    transformTranslation(input: TransformationInput): Promise<TransformationOutput>;
    translateText(text: string, targetLang: string): Promise<string>;
    updateRequestStatus(requestId: RequestId, status: RequestStatus): Promise<boolean>;
}
import type { Assignment as _Assignment, AssignmentId as _AssignmentId, AssignmentStatus as _AssignmentStatus, ChatMessage as _ChatMessage, ChatRole as _ChatRole, CreateRequestInput as _CreateRequestInput, NgoId as _NgoId, RequestId as _RequestId, RequestStatus as _RequestStatus, ResourceRequest as _ResourceRequest, ResourceType as _ResourceType, Timestamp as _Timestamp, Urgency as _Urgency, VolunteerId as _VolunteerId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignVolunteer(arg0: RequestId, arg1: VolunteerId): Promise<Assignment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.assignVolunteer(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignVolunteer(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRequest(arg0: CreateRequestInput): Promise<ResourceRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createRequest(to_candid_CreateRequestInput_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResourceRequest_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRequest(to_candid_CreateRequestInput_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResourceRequest_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async detectLanguage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.detectLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectLanguage(arg0);
            return result;
        }
    }
    async getAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNGOs(): Promise<Array<NGO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNGOs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNGOs();
            return result;
        }
    }
    async getAllRequests(): Promise<Array<ResourceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVolunteers(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVolunteers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVolunteers();
            return result;
        }
    }
    async getAvailableVolunteers(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableVolunteers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableVolunteers();
            return result;
        }
    }
    async getMapApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMapApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMapApiKey();
            return result;
        }
    }
    async getNearbyRequests(arg0: number, arg1: number, arg2: number): Promise<Array<ResourceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyRequests(arg0, arg1, arg2);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyRequests(arg0, arg1, arg2);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsByNgo(arg0: NgoId): Promise<Array<ResourceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsByNgo(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsByNgo(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerNGO(arg0: CreateNGOInput): Promise<NGO> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNGO(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNGO(arg0);
            return result;
        }
    }
    async registerVolunteer(arg0: CreateVolunteerInput): Promise<Volunteer> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVolunteer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVolunteer(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: Array<ChatMessage>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(to_candid_vec_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(to_candid_vec_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setGeminiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGeminiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGeminiApiKey(arg0);
            return result;
        }
    }
    async setGoogleCloudTranslationApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGoogleCloudTranslationApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGoogleCloudTranslationApiKey(arg0);
            return result;
        }
    }
    async setGoogleMapsApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGoogleMapsApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGoogleMapsApiKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async transformTranslation(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformTranslation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformTranslation(arg0);
            return result;
        }
    }
    async translateText(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.translateText(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.translateText(arg0, arg1);
            return result;
        }
    }
    async updateRequestStatus(arg0: RequestId, arg1: RequestStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(arg0, to_candid_RequestStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(arg0, to_candid_RequestStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AssignmentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentStatus): AssignmentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Assignment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceRequest): ResourceRequest {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Urgency_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Urgency): Urgency {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Assignment]): Assignment | null {
    return value.length === 0 ? null : from_candid_Assignment_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RequestId;
    lat: number;
    lng: number;
    status: _RequestStatus;
    title: string;
    urgency: _Urgency;
    assignedVolunteers: Array<_VolunteerId>;
    createdAt: _Timestamp;
    description: string;
    deadline: _Timestamp;
    resourceType: _ResourceType;
    ngoId: _NgoId;
    quantity: bigint;
}): {
    id: RequestId;
    lat: number;
    lng: number;
    status: RequestStatus;
    title: string;
    urgency: Urgency;
    assignedVolunteers: Array<VolunteerId>;
    createdAt: Timestamp;
    description: string;
    deadline: Timestamp;
    resourceType: ResourceType;
    ngoId: NgoId;
    quantity: bigint;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        status: from_candid_RequestStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        urgency: from_candid_Urgency_n17(_uploadFile, _downloadFile, value.urgency),
        assignedVolunteers: value.assignedVolunteers,
        createdAt: value.createdAt,
        description: value.description,
        deadline: value.deadline,
        resourceType: from_candid_ResourceType_n19(_uploadFile, _downloadFile, value.resourceType),
        ngoId: value.ngoId,
        quantity: value.quantity
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssignmentId;
    status: _AssignmentStatus;
    completedAt: [] | [_Timestamp];
    requestId: _RequestId;
    volunteerId: _VolunteerId;
    acceptedAt: _Timestamp;
}): {
    id: AssignmentId;
    status: AssignmentStatus;
    completedAt?: Timestamp;
    requestId: RequestId;
    volunteerId: VolunteerId;
    acceptedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_AssignmentStatus_n4(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.completedAt)),
        requestId: value.requestId,
        volunteerId: value.volunteerId,
        acceptedAt: value.acceptedAt
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    ongoing: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "completed" in value ? RequestStatus.completed : "ongoing" in value ? RequestStatus.ongoing : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Urgency {
    return "low" in value ? Urgency.low : "high" in value ? Urgency.high : "critical" in value ? Urgency.critical : "medium" in value ? Urgency.medium : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    food: null;
} | {
    education: null;
} | {
    shelter: null;
} | {
    medical: null;
}): ResourceType {
    return "other" in value ? ResourceType.other : "food" in value ? ResourceType.food : "education" in value ? ResourceType.education : "shelter" in value ? ResourceType.shelter : "medical" in value ? ResourceType.medical : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): AssignmentStatus {
    return "active" in value ? AssignmentStatus.active : "cancelled" in value ? AssignmentStatus.cancelled : "completed" in value ? AssignmentStatus.completed : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResourceRequest>): Array<ResourceRequest> {
    return value.map((x)=>from_candid_ResourceRequest_n13(_uploadFile, _downloadFile, x));
}
function to_candid_ChatMessage_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatMessage): _ChatMessage {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ChatRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): _ChatRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_CreateRequestInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRequestInput): _CreateRequestInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_RequestStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): _ResourceType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Urgency_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Urgency): _Urgency {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: ChatRole;
    timestamp: Timestamp;
}): {
    content: string;
    role: _ChatRole;
    timestamp: _Timestamp;
} {
    return {
        content: value.content,
        role: to_candid_ChatRole_n26(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    title: string;
    urgency: Urgency;
    description: string;
    deadline: Timestamp;
    resourceType: ResourceType;
    ngoId: NgoId;
    quantity: bigint;
}): {
    lat: number;
    lng: number;
    title: string;
    urgency: _Urgency;
    description: string;
    deadline: _Timestamp;
    resourceType: _ResourceType;
    ngoId: _NgoId;
    quantity: bigint;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        title: value.title,
        urgency: to_candid_Urgency_n9(_uploadFile, _downloadFile, value.urgency),
        description: value.description,
        deadline: value.deadline,
        resourceType: to_candid_ResourceType_n11(_uploadFile, _downloadFile, value.resourceType),
        ngoId: value.ngoId,
        quantity: value.quantity
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Urgency): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Urgency.low ? {
        low: null
    } : value == Urgency.high ? {
        high: null
    } : value == Urgency.critical ? {
        critical: null
    } : value == Urgency.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): {
    other: null;
} | {
    food: null;
} | {
    education: null;
} | {
    shelter: null;
} | {
    medical: null;
} {
    return value == ResourceType.other ? {
        other: null
    } : value == ResourceType.food ? {
        food: null
    } : value == ResourceType.education ? {
        education: null
    } : value == ResourceType.shelter ? {
        shelter: null
    } : value == ResourceType.medical ? {
        medical: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): {
    user: null;
} | {
    assistant: null;
} {
    return value == ChatRole.user ? {
        user: null
    } : value == ChatRole.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    pending: null;
} | {
    completed: null;
} | {
    ongoing: null;
} {
    return value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.completed ? {
        completed: null
    } : value == RequestStatus.ongoing ? {
        ongoing: null
    } : value;
}
function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ChatMessage>): Array<_ChatMessage> {
    return value.map((x)=>to_candid_ChatMessage_n24(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
